---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: communication
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./continuwuity/ks.yaml
  - ./coturn/ks.yaml
  - ./element-web/ks.yaml
  - ./lavalink/ks.yaml
  - ./livekit/ks.yaml
  - ./mumble/ks.yaml
  - ./redbot/ks.yaml
