---
# NOTE: Multi-source - configure Secret Imports in Infisical for: nextcloud, protonmail
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name nextcloud-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/self-hosted/nextcloud
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: self-hosted
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          nextcloud-username: '{{ .ADMIN_USER.Value }}'
          nextcloud-password: '{{ .ADMIN_PASS.Value }}'
          smtp_host: '{{ .SMTP_ADDR.Value }}'
          smtp_username: '{{ .SMTP_USER.Value }}'
          smtp_password: '{{ .SMTP_PASS.Value }}'
          OIDC_CLIENT_ID: '{{ .NEXTCLOUD_CLIENT_ID.Value }}'
          OIDC_CLIENT_SECRET: '{{ .NEXTCLOUD_CLIENT_SECRET.Value }}'
