---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name wazuh-credentials
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/security/wazuh
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: security
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          INDEXER_USERNAME: '{{ .INDEXER_USERNAME.Value }}'
          INDEXER_PASSWORD: '{{ .INDEXER_PASSWORD.Value }}'
          INDEXER_PASSWORD_HASH: '{{ .INDEXER_PASSWORD_HASH.Value }}'
          DASHBOARD_USERNAME: '{{ .DASHBOARD_USERNAME.Value }}'
          DASHBOARD_PASSWORD: '{{ .DASHBOARD_PASSWORD.Value }}'
          DASHBOARD_PASSWORD_HASH: '{{ .DASHBOARD_PASSWORD_HASH.Value }}'
          API_USERNAME: '{{ .API_USERNAME.Value }}'
          API_PASSWORD: '{{ .API_PASSWORD.Value }}'
          authd.pass: '{{ (index . "authd.pass").Value }}'
