---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omnichassis
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./rbac.yaml
  - ./fleet/ks.yaml
  - ./infra/ks.yaml
  - ./sil-runner/ks.yaml
