---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name dawarich-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/self-hosted/dawarich
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: ${NS}
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          SECRET_KEY_BASE: '{{ .SECRET_KEY_BASE.Value }}'
          METRICS_USERNAME: '{{ .METRICS_USERNAME.Value }}'
          METRICS_PASSWORD: '{{ .METRICS_PASSWORD.Value }}'
