---
# NOTE: Configure Secret Imports in Infisical from /terraform/authentik/oidc
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name sparkyfitness-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/self-hosted/sparkyfitness
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: self-hosted
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          SPARKY_FITNESS_API_ENCRYPTION_KEY: '{{ .SPARKY_FITNESS_API_ENCRYPTION_KEY.Value }}'
          BETTER_AUTH_SECRET: '{{ .BETTER_AUTH_SECRET.Value }}'
          SPARKY_FITNESS_OIDC_CLIENT_ID: '{{ .SPARKYFITNESS_CLIENT_ID.Value }}'
          SPARKY_FITNESS_OIDC_CLIENT_SECRET: '{{ .SPARKYFITNESS_CLIENT_SECRET.Value }}'
