set unstable
set quiet
set script-interpreter := ['bash', '-euo', 'pipefail']
set shell := ['bash', '-euo', 'pipefail', '-c']

[confirm('Bootstrap Talos nodes and cluster apps from scratch [y|N] ?')]
[doc('Bootstrap Talos nodes and Cluster apps')]
default:
    #!/usr/bin/env bash
    set -euo pipefail
    script="{{ parent_directory(source_directory()) }}/scripts/bootstrap-cluster.sh"
    test -f "$script"
    find --version | grep -q GNU
    command -v gum helm helmfile kubectl infisical talosctl yq >/dev/null
    bash "$script"
