---
name: towonel-agent

services:
  towonel-agent:
    # renovate: datasource=docker depName=codeberg.org/towonel/towonel-agent
    image: codeberg.org/towonel/towonel-agent:1.4.1
    container_name: towonel-agent
    restart: unless-stopped
    labels:
      net.unraid.docker.icon: "https://codeberg.org/towonel.png"
    environment:
      RUST_LOG: info
      TOWONEL_INVITE_TOKEN: ${TOWONEL_INVITE_TOKEN}
      TOWONEL_AGENT_HEALTH_LISTEN_ADDR: 0.0.0.0:9090
      TOWONEL_AGENT_RELAY_URL: "https://relay.towonel.vzkn.eu/,https://relay.towonel.erwanleboucher.dev/,https://euc1-1.relay.n0.iroh-canary.iroh.link/"
      TOWONEL_AGENT_SERVICES: >-
        [
          {"hostname":"emby.vzkn.eu","origin":"caddy:443","proxy_protocol":"v2"},
          {"hostname":"music.vzkn.eu","origin":"caddy:443","proxy_protocol":"v2"}
        ]
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 32m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: aincrad
    external: true
