---
# yaml-language-server: $schema=https://schemas.vzkn.eu/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: newt
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.2.0
  url: oci://ghcr.io/home-operations/charts-mirror/newt
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: newt
  values:
    global:
      deploymentAnnotations:
        reloader.stakater.com/auto: "true"
      image:
        tag: 1.10.3
      nativeMode:
        enabled: true
      nodeSelector:
        topology.kubernetes.io/zone: worker

    rbac:
      clusterRole: true

    serviceAccount:
      automountServiceAccountToken: true
      name: newt

    newtInstances:
      - name: main-tunnel
        enabled: true
        replicas: 1
        auth:
          existingSecretName: newt-secret
          keys:
            endpointKey: NEWT_SERVER_URL
        extraEnv:
          BLUEPRINT_FILE: /etc/newt/blueprint.yaml
          NEWT_ADMIN_ADDR: "0.0.0.0:2112"
          NEWT_METRICS_PROMETHEUS_ENABLED: "true"
        extraVolumeMounts:
          - name: blueprint
            mountPath: /etc/newt
        extraVolumes:
          - name: blueprint
            emptyDir: {}
        initContainers:
          - name: newt-sidecar
            image: ghcr.io/home-operations/newt-sidecar:0.2.0
            args:
              - --gateway-name=envoy-external
              - --site-id=lonely-northern-pika
              - --target-hostname=10.10.0.91
              - --deny-countries=RU,CN,KP,IR,BY,KZ,UZ,TM,TJ,KG,AM,AZ,SY,IQ,SA,KW,BH,QA,AE,OM,YE,AF,PK,BD,MM,MN
            restartPolicy: Always
            resources:
              limits:
                memory: 128Mi
            volumeMounts:
              - name: blueprint
                mountPath: /etc/newt
          - name: wait-blueprint
            image: ghcr.io/home-operations/busybox:1.37.0@sha256:026ed7273270ec08f6902b4ae8334c23b473e5394bec3bbbdbfe580c710d50bc
            command:
              - /bin/sh
              - -c
              - until test -f /etc/newt/blueprint.yaml; do sleep 1; done
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 16Mi
            volumeMounts:
              - name: blueprint
                mountPath: /etc/newt
        metrics:
          port: 2112
          service:
            enabled: true
            port: 2112
          serviceMonitor:
            enabled: true
        pingInterval: 60s
        service:
          enabled: false
        hostNetwork: true
        useNativeInterface: true
