---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name newt-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/network/newt
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: network
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          NEWT_ID: "{{ .NEWT_ID.Value }}"
          NEWT_SECRET: "{{ .NEWT_SECRET.Value }}"
          NEWT_SERVER_URL: "{{ .NEWT_SERVER_URL.Value }}"
          VPS_IP: "{{ .VPS_IP.Value }}"
