[env]
# File paths
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

_.file = ["{{config_root}}/.secrets.env"]

[hooks]
postinstall = "lefthook install"

[tools]
actionlint = "1.7.12"
flux2 = "2.8.8"
helm = "3.20.2"
helmfile = "1.5.5"
infisical = "0.41.99"
jq = "1.8.2"
just = "1.51.0"
kubectl = "1.36.2"
kustomize = "5.8.1"
lefthook = "1.13.6"
shellcheck = "0.11.0"
talosctl = "1.13.10"
task = "3.48.0"
uv = "latest"
yamlfmt = "0.21.0"
zizmor = "1.30.1"
"github:home-operations/flate" = "v0.6.5"
"github:mitsuhiko/minijinja" = "2.20.0"
"pipx:flux-local" = "8.2.0"
