---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalpushsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: vzkn-eu-tls
spec:
  resyncInterval: 1h
  hostAPI: https://eu.infisical.com/api
  updatePolicy: Replace
  deletionPolicy: Delete
  destination:
    projectSlug: vzkn-eu-v2-zn
    environmentSlug: prod
    secretsPath: /kubernetes/network/certificates-import
  push:
    secret:
      secretName: vzkn-eu-tls
      secretNamespace: network
      template:
        includeAllSecrets: false
        data:
          TLS_CRT: '{{ (index . "tls.crt").Value | b64enc }}'
          TLS_KEY: '{{ (index . "tls.key").Value | b64enc }}'
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
