---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name livekit-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        livekit.yaml: |
          port: 7880
          rtc:
            port_range_start: 50100
            port_range_end: 50200
            tcp_port: 7881
            use_external_ip: true
          redis:
            address: livekit-dragonfly:6379
          keys:
            {{ .LIVEKIT_KEY }}: {{ .LIVEKIT_SECRET }}
          logging:
            level: info
          turn:
            enabled: true
            domain: turn.vzkn.eu
            tls_port: 5349
            udp_port: 3478
            external_tls: true
        LIVEKIT_KEY: "{{ .LIVEKIT_KEY }}"
        LIVEKIT_SECRET: "{{ .LIVEKIT_SECRET }}"
  dataFrom:
    - extract:
        key: livekit
