---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name livekit-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/communication/livekit
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: communication
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          livekit.yaml: |
            port: 7880
            rtc:
              port_range_start: 50100
              port_range_end: 50200
              tcp_port: 7881
              use_external_ip: true
            redis:
              address: livekit-dragonfly:6379
            keys:
              {{ .LIVEKIT_KEY.Value }}: {{ .LIVEKIT_SECRET.Value }}
            logging:
              level: info
            turn:
              enabled: true
              domain: turn.vzkn.eu
              tls_port: 5349
              udp_port: 3478
              external_tls: true
          LIVEKIT_KEY: '{{ .LIVEKIT_KEY.Value }}'
          LIVEKIT_SECRET: '{{ .LIVEKIT_SECRET.Value }}'
