---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name livekit-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/communication/livekit
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: communication
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          livekit.yaml: |
            port: 7880
            bind_addresses:
              - ""
            rtc:
              tcp_port: 7881
              port_range_start: 50100
              port_range_end: 50110
              ips:
                includes:
                  - 10.69.0.0/16
              stun_servers:
                - turn.vzkn.eu:3478
              turn_servers:
                - host: turn.vzkn.eu
                  port: 5349
                  protocol: tls
                  secret: '{{ .TURN_SECRET.Value }}'
                - host: turn.vzkn.eu
                  port: 3478
                  protocol: udp
                  secret: '{{ .TURN_SECRET.Value }}'
              use_external_ip: false
              enable_loopback_candidate: false
            redis:
              address: livekit-dragonfly:6379
            keys:
              {{ .LIVEKIT_KEY.Value }}: {{ .LIVEKIT_SECRET.Value }}
            room:
              auto_create: false
            turn:
              enabled: false
            logging:
              level: info
          LIVEKIT_KEY: '{{ .LIVEKIT_KEY.Value }}'
          LIVEKIT_SECRET: '{{ .LIVEKIT_SECRET.Value }}'
