---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mikrotik-cert-sync-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/network/mikrotik-cert-sync
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: mikrotik-cert-sync-secret
      secretNamespace: network
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          SSH_PRIVATE_KEY: '{{ .MIKROTIK_SSH_PRIVATE_KEY.Value }}'
