---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vzkn-eu-tls
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: vzkn-eu-tls
    creationPolicy: Orphan
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: INGRESS_NGINX_TLS_CRT
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: INGRESS_NGINX_TLS_KEY
        property: tls.key
