---
# NOTE: Uses same TLS cert as network/certificates-import - use Secret Import from /kubernetes/network/certificates-import
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name vzkn-eu-tls
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/communication/coturn-tls
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: communication
      secretType: kubernetes.io/tls
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          tls.crt: '{{ index .TLS_CRT "Value" }}'
          tls.key: '{{ index .TLS_KEY "Value" }}'
