---
# NOTE: Multi-source - configure Secret Imports in Infisical for: pgadmin, cloudnative-pg
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name pgadmin-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/database/pgadmin
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: database
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          PGADMIN_DEFAULT_EMAIL: '{{ .PGADMIN_DEFAULT_EMAIL.Value }}'
          PGADMIN_DEFAULT_PASSWORD: '{{ .PGADMIN_DEFAULT_PASSWORD.Value }}'
          config_local.py: |
            import os
            AUTHENTICATION_SOURCES = ['oauth2']
            OAUTH2_AUTO_CREATE_USER = True
            MASTER_PASSWORD_REQUIRED = False
            OAUTH2_CONFIG = [{
                'OAUTH2_NAME': 'kanidm',
                'OAUTH2_DISPLAY_NAME': 'Login with Kanidm',
                # Client id/secret injected as env vars from k8s Secret kanidm-pgadmin-oidc
                'OAUTH2_CLIENT_ID': os.environ['OAUTH2_CLIENT_ID'],
                'OAUTH2_CLIENT_SECRET': os.environ['OAUTH2_CLIENT_SECRET'],
                'OAUTH2_TOKEN_URL': 'https://idm.vzkn.eu/oauth2/token',
                'OAUTH2_AUTHORIZATION_URL': 'https://idm.vzkn.eu/ui/oauth2',
                'OAUTH2_API_BASE_URL': 'https://idm.vzkn.eu/oauth2/openid/pgadmin/',
                'OAUTH2_USERINFO_ENDPOINT': 'https://idm.vzkn.eu/oauth2/openid/pgadmin/userinfo',
                'OAUTH2_SERVER_METADATA_URL': 'https://idm.vzkn.eu/oauth2/openid/pgadmin/.well-known/openid-configuration',
                'OAUTH2_SCOPE': 'openid email profile',
                'OAUTH2_ICON': 'fa-openid',
                'OAUTH2_BUTTON_COLOR': '#fd4b2d'
            }]
          pgpass: |
            *:*:*:{{ .POSTGRES_SUPER_USER.Value }}:{{ .POSTGRES_SUPER_PASS.Value }}
          servers.json: |-
            {
              "Servers": {
                "1": {
                  "Name": "forgejo",
                  "Group": "development",
                  "Host": "postgres-forgejo-rw.development.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "10": {
                  "Name": "bazarr",
                  "Group": "downloads",
                  "Host": "postgres-bazarr-rw.downloads.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "11": {
                  "Name": "prowlarr",
                  "Group": "downloads",
                  "Host": "postgres-prowlarr-rw.downloads.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "12": {
                  "Name": "radarr",
                  "Group": "downloads",
                  "Host": "postgres-radarr-rw.downloads.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "13": {
                  "Name": "sonarr",
                  "Group": "downloads",
                  "Host": "postgres-sonarr-rw.downloads.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "20": {
                  "Name": "jellystat",
                  "Group": "media",
                  "Host": "postgres-jellystat-rw.media.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "21": {
                  "Name": "seerr",
                  "Group": "media",
                  "Host": "postgres-seerr-rw.media.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "30": {
                  "Name": "authentik",
                  "Group": "security",
                  "Host": "postgres-authentik-rw.security.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "40": {
                  "Name": "nextcloud",
                  "Group": "self-hosted",
                  "Host": "postgres-nextcloud-rw.self-hosted.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                },
                "41": {
                  "Name": "rxresume",
                  "Group": "self-hosted",
                  "Host": "postgres-rxresume-rw.self-hosted.svc.cluster.local",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "SharedUsername": "{{ .POSTGRES_SUPER_USER.Value }}",
                  "Shared": true,
                  "SSLMode": "prefer",
                  "PassFile": ".pgpass"
                }
              }
            }
