---
# NOTE: Multi-source - configure Secret Imports in Infisical for: jellystat, maxmind
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name jellystat-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/media/jellystat
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: media
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          JWT_SECRET: '{{ .JWT_SECRET.Value }}'
          JS_GEOLITE_ACCOUNT_ID: '{{ .MAXMIND_USER_ID.Value }}'
          JS_GEOLITE_LICENSE_KEY: '{{ .MAXMIND_LICENSE_KEY.Value }}'
