---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalpushsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: headlamp-admin
spec:
  resyncInterval: 1h
  hostAPI: https://eu.infisical.com/api
  updatePolicy: Replace
  destination:
    projectSlug: vzkn-eu-v2-zn
    environmentSlug: prod
    secretsPath: /kubernetes/flux-system/headlamp
  push:
    secret:
      secretName: headlamp-admin
      secretNamespace: flux-system
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
