---
directories:
  downloads: /soulseek/complete
  incomplete: /soulseek/incomplete
flags:
  no_version_check: true
integration:
  vpn:
    enabled: true
    port_forwarding: true
    polling_interval: 2500
    gluetun:
      url: http://localhost:8000
      timeout: 1000
metrics:
  enabled: true
  url: /metrics
  authentication:
    disabled: true
permissions:
  file:
    mode: 750
remote_configuration: false
shares:
  directories:
    - /soulseek/shared
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
web:
  authentication:
    api_keys:
      my_api_key:
        key: ${SLSKD_API_KEY}
        cidr: 0.0.0.0/0,::/0
