---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-operator
spec:
  interval: 1h
  path: ./kubernetes/apps/development/tekton/operator
  healthCheckExprs:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: development
  wait: true
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-config
spec:
  interval: 1h
  path: ./kubernetes/apps/development/tekton/config
  dependsOn:
    - name: tekton-operator
  healthCheckExprs:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonConfig
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-pac
spec:
  interval: 1h
  path: ./kubernetes/apps/development/tekton/pac
  dependsOn:
    - name: tekton-config
  healthCheckExprs:
    - apiVersion: apps/v1
      kind: Deployment
      failed: status.availableReplicas == 0
      current: status.availableReplicas == status.replicas
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tekton-results
spec:
  components:
    - ../../../../components/cnpg/initdb
  interval: 1h
  path: ./kubernetes/apps/development/tekton/results
  dependsOn:
    - name: infisical-operator
      namespace: security
    - name: plugin-barman-cloud
      namespace: database
    - name: tekton-operator
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonResult
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  postBuild:
    substitute:
      APP: *app
      NS: &ns tekton-pipelines
      CNPG_SIZE: 2Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *ns
  wait: false
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-shared-tasks
spec:
  interval: 1h
  path: ./kubernetes/apps/development/tekton/shared-tasks
  dependsOn:
    - name: tekton-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
