---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name slskd-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/downloads/slskd
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: downloads
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          SLSKD_SLSK_USERNAME: '{{ .SLSKD_SLSK_USERNAME.Value }}'
          SLSKD_SLSK_PASSWORD: '{{ .SLSKD_SLSK_PASSWORD.Value }}'
          SLSKD_API_KEY: '{{ .SLSKD_API_KEY.Value }}'
          SLSKD_VPN_GLUETUN_API_KEY: '{{ .GLUETUN_API_KEY.Value }}'
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name slskd-vpn-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/downloads/slskd-vpn
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: downloads
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          WIREGUARD_PRIVATE_KEY: '{{ .WIREGUARD_PRIVATE_KEY.Value }}'
          WIREGUARD_ADDRESSES: '{{ .WIREGUARD_ADDRESSES.Value }}'
          HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: '{"auth":"apikey","apikey":"{{ .GLUETUN_API_KEY.Value }}"}'
