---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
# NOTE: Multi-source - configure Secret Imports in Infisical for: harbor, /terraform/garage/buckets
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name harbor-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/development/harbor
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: development
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          HARBOR_ADMIN_PASSWORD: '{{ .HARBOR_ADMIN_PASSWORD.Value }}'
          REGISTRY_STORAGE_S3_ACCESSKEY: '{{ .HARBOR_ACCESS_KEY_ID.Value }}'
          REGISTRY_STORAGE_S3_SECRETKEY: '{{ .HARBOR_SECRET_ACCESS_KEY.Value }}'
          secretKey: '{{ .ENCRYPTION_KEY.Value }}'
          REGISTRY_PASSWD: '{{ .REGISTRY_PASSWORD.Value }}'
          REGISTRY_HTPASSWD: '{{ .REGISTRY_HTPASSWD.Value }}'
