---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name cloudflare-dns
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/network/cloudflare-dns
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: network
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          CF_API_TOKEN: '{{ .CLOUDFLARE_DNS_TOKEN.Value }}'
          CF_ZONE_ID: '{{ .CLOUDFLARE_ZONE_ID.Value }}'
