---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: nix-config-pac-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/development/nix-config-pac
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: nix-config-pac-secret
      secretNamespace: development
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          provider.token: '{{ .FORGEJO_PAT.Value }}'
          webhook.secret: '{{ .WEBHOOK_SECRET.Value }}'
