---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app heisenbridge
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/kopiur
  dependsOn:
    - name: continuwuity
      namespace: communication
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/communication/heisenbridge
  postBuild:
    substitute:
      APP: *app
      NS: &ns communication
      KOPIUR_CAPACITY: 1Gi
      KOPIUR_PUID: "1337"
      KOPIUR_PGID: "1337"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *ns
  wait: false
