---
# NOTE: Multi-source - configure Secret Imports in Infisical for: authentik, protonmail
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name authentik-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/security/authentik
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: security
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          AUTHENTIK_BOOTSTRAP_EMAIL: '{{ .AUTHENTIK_EMAIL.Value }}'
          AUTHENTIK_BOOTSTRAP_PASSWORD: '{{ .AUTHENTIK_PASSWORD.Value }}'
          AUTHENTIK_BOOTSTRAP_TOKEN: '{{ .AUTHENTIK_TOKEN.Value }}'
          AUTHENTIK_SECRET_KEY: '{{ .AUTHENTIK_SECRET_KEY.Value }}'
          AUTHENTIK_EMAIL__HOST: '{{ .SMTP_HOST.Value }}'
          AUTHENTIK_EMAIL__PORT: "587"
          AUTHENTIK_EMAIL__USERNAME: '{{ .SMTP_USER.Value }}'
          AUTHENTIK_EMAIL__PASSWORD: '{{ .SMTP_PASS.Value }}'
          AUTHENTIK_EMAIL__USE_TLS: "true"
          AUTHENTIK_EMAIL__USE_SSL: "false"
          AUTHENTIK_EMAIL__TIMEOUT: "10"
          AUTHENTIK_EMAIL__FROM: "authentik@vzkn.eu"
