---
# yaml-language-server: $schema=https://schemas.vzkn.eu/stunner.l7mp.io/gatewayconfig_v1.json
apiVersion: stunner.l7mp.io/v1
kind: GatewayConfig
metadata:
  name: stunner
spec:
  authRef:
    name: stunner-auth
    namespace: network
  logLevel: "all:INFO"
  realm: stunner.vzkn.eu
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/gateway.networking.k8s.io/gatewayclass_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: stunner
spec:
  controllerName: stunner.l7mp.io/gateway-operator
  description: STUNner is a WebRTC ingress gateway for Kubernetes
  parametersRef:
    group: stunner.l7mp.io
    kind: GatewayConfig
    name: stunner
    namespace: network
