---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name home-ops-runner-secret
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/actions-runner-system/actions-runner-controller
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: actions-runner-system
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          github_app_id: '{{ .ACTIONS_RUNNER_APP_ID.Value }}'
          github_app_installation_id: '{{ .ACTIONS_RUNNER_INSTALLATION_ID.Value }}'
          github_app_private_key: '{{ .ACTIONS_RUNNER_PRIVATE_KEY.Value }}'
