---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name sentry-forgejo-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/sentry/sentry-forgejo
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: sentry
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          SENTRY_CLIENT_SECRET: '{{ .SENTRY_CLIENT_SECRET.Value }}'
          SENTRY_AUTH_TOKEN: '{{ .SENTRY_AUTH_TOKEN.Value }}'
          # Forgejo side
          FORGEJO_TOKEN: '{{ .FORGEJO_TOKEN.Value }}'
          FORGEJO_WEBHOOK_SECRET: '{{ .FORGEJO_WEBHOOK_SECRET.Value }}'
          # Flask session signing
          APP_SECRET_KEY: '{{ .APP_SECRET_KEY.Value }}'
