---
alerting:
  pushover:
    application-token: ${PUSHOVER_TOKEN}
    user-key: ${PUSHOVER_USER_KEY}
    title: Gatus | bifrost
    priority: 1
    resolved-priority: 0
    default-alert:
      description: health-check failed
      failure-threshold: 3
      success-threshold: 2
      send-on-resolved: true
      minimum-reminder-interval: 1h

endpoints:
  - name: status page
    group: home
    url: https://${REMOTE_STATUS_HOSTNAME}
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

external-endpoints:
  - name: heartbeat
    group: home
    token: ${REMOTE_HEARTBEAT_TOKEN}
    heartbeat:
      interval: 5m
    alerts:
      - type: pushover

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Status | bifrost
  header: Status
  link: https://github.com/vrozaksen

web:
  port: ${GATUS_WEB_PORT}
