---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      qbittorrent:
        replicas: 1
        strategy: Recreate
        labels:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.4@sha256:bb82ad6668f8eda1d0fcce6c1341498bfa879155bb1295cd9d314a2c35c07a01
            env:
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 54535
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                10.69.0.0/16, 10.10.0.0/24
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__UseUPNP: false
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__RootFolder: ""
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                spec:
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
    defaultPodOptions:
      terminationGracePeriodSeconds: 300
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    service:
      qbittorrent:
        primary: true
        ports:
          http:
            port: *port
      bittorrent:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.10.0.41
        externalTrafficPolicy: Local
        ports:
          bittorrent-tcp:
            port: *torrentPort
            protocol: TCP
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: downloads
        hostnames:
          - qb.vzkn.eu
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: qbittorrent
                port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      data:
        type: nfs
        server: aincrad.home.vzkn.eu
        path: /mnt/user/data/torrents
        globalMounts:
          - path: /downloads
      tmp:
        type: emptyDir
