---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
spec:
  discoveryFilter: "vrozaksen/*"
  provider:
    name: github
  image: ghcr.io/renovatebot/renovate:43.141.6@sha256:f3a911a9d1492b67f1eccd9edf2cc60049ca4b6340610a42616a095cb1a55afa
  schedule: "0 * * * *"
  parallelism: 3
  secretRef: renovate-token
  extraEnv:
    - name: LOG_LEVEL
      value: info
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  webhook:
    enabled: true
    authentication:
      enabled: false
