---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
spec:
  discoveryFilter: "vrozaksen/*"
  provider:
    name: github
  image: ghcr.io/renovatebot/renovate:43.76.5@sha256:5907c7637ca9fb53efeb91f5369f55a32b4a5c74164e76a6417ce133fa6eeea0
  schedule: "0 * * * *"
  parallelism: 3
  secretRef: renovate-token
  extraEnv:
    - name: LOG_LEVEL
      value: info
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  webhook:
    enabled: true
    authentication:
      enabled: false
