---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
spec:
  discoveryFilter: "vrozaksen/*"
  provider:
    name: github
  image: ghcr.io/renovatebot/renovate:43.84.2@sha256:3d38849d5bbd100e14cd296b04e77579dbfb981f38a98946dbeab961d18d498d
  schedule: "0 * * * *"
  parallelism: 3
  secretRef: renovate-token
  extraEnv:
    - name: LOG_LEVEL
      value: info
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  webhook:
    enabled: true
    authentication:
      enabled: false
