---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./infisicalsecret.yaml
  - ./token-refresh.yaml
  - ./home-ops.yaml
  - ./infisicalsecret-forgejo.yaml
  - ./forgejo.yaml
