---
# yaml-language-server: $schema=https://schemas.vzkn.eu/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: prometheus
spec:
  oidc:
    provider:
      issuer: https://idm.vzkn.eu/oauth2/openid/prometheus
    clientID: prometheus
    clientSecret:
      name: kanidm-prometheus-oidc  # secret written by kanidm-provision, key client-secret
    redirectURL: https://prometheus.vzkn.eu/oauth2/callback
    logoutPath: /logout
    cookieDomain: prometheus.vzkn.eu
    scopes:
      - "openid"
      - "email"
      - "profile"
      - "groups"
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kube-prometheus-stack-prometheus
