---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./infisicalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml

secretGenerator:
  - name: defectdojo-valkey-specific
    literals:
      - valkey-password=""
    options:
      disableNameSuffixHash: true
