---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name mautrix-meta-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/communication/mautrix-meta
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: communication
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          MAUTRIX_META_APPSERVICE__AS_TOKEN: '{{ .AS_TOKEN.Value }}'
          MAUTRIX_META_APPSERVICE__HS_TOKEN: '{{ .HS_TOKEN.Value }}'
          MAUTRIX_META_ENCRYPTION__PICKLE_KEY: '{{ .PICKLE_KEY.Value }}'
          MAUTRIX_META_PROVISIONING__SHARED_SECRET: '{{ .PROVISIONING_TOKEN.Value }}'
          MAUTRIX_META_DOUBLE_PUPPET__SECRETS__VZKN__EU: 'as_token:{{ .AS_TOKEN.Value }}'
