---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name vmcp-authentik-oidc
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /terraform/authentik/oidc
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: ai
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          client-secret: '{{ .MCP_GATEWAY_CLIENT_SECRET.Value }}'
          MCP_GATEWAY_CLIENT_ID: '{{ .MCP_GATEWAY_CLIENT_ID.Value }}'
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name vmcp-auth-server-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/ai/toolhive
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: ai
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          signing-key: '{{ .VMCP_SIGNING_KEY.Value }}'
          hmac-key: '{{ .VMCP_HMAC_KEY.Value }}'
