---
# yaml-language-server: $schema=https://schemas.vzkn.eu/toolhive.stacklok.dev/mcpoidcconfig_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPOIDCConfig
metadata:
  name: external-oidc
spec:
  type: inline
  inline:
    issuer: https://mcp.vzkn.eu
    jwksAllowPrivateIP: true
    protectedResourceAllowPrivateIP: true
