---
# yaml-language-server: $schema=https://schemas.vzkn.eu/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mcp-gateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: virtualmcpserver
      app.kubernetes.io/instance: mcp-gateway
  namespaceSelector:
    matchNames:
      - ai
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
