---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./db
  - ./helmrelease.yaml
  - ./pvc.yaml
patches:
  - path: ./patches/cluster-vectorchord.yaml
  - path: ./patches/dragonfly-bullmq.yaml
