---
# NOTE: Bootstrap fallback - imports TLS cert from Infisical
# In Infisical, store tls.crt and tls.key as separate secrets in /kubernetes/network/certificates-import/
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name vzkn-eu-tls
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 0s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/network/certificates-import
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: network
      secretType: kubernetes.io/tls
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        metadata:
          annotations:
            cert-manager.io/alt-names: "*.vzkn.eu,vzkn.eu,*.s3.vzkn.eu"
            cert-manager.io/certificate-name: vzkn.eu
            cert-manager.io/common-name: vzkn.eu
            cert-manager.io/ip-sans: ""
            cert-manager.io/issuer-group: ""
            cert-manager.io/issuer-kind: ClusterIssuer
            cert-manager.io/issuer-name: letsencrypt-production
            cert-manager.io/uri-sans: ""
          labels:
            controller.cert-manager.io/fao: "true"
        data:
          tls.crt: '{{ index .TLS_CRT "Value" }}'
          tls.key: '{{ index .TLS_KEY "Value" }}'
