---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
# Secret names are fixed by the chart's existingSecrets convention.
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: step-ca-secrets
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/security/step-ca
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: step-ca-step-certificates-certs
      secretNamespace: security
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          root_ca.crt: '{{ .ROOT_CA_CRT.Value }}'
          intermediate_ca.crt: '{{ .INTERMEDIATE_CA_CRT.Value }}'
          ssh_user_ca_key.pub: '{{ .SSH_USER_CA_PUB.Value }}'
          ssh_host_ca_key.pub: '{{ .SSH_HOST_CA_PUB.Value }}'
    - secretName: step-ca-step-certificates-secrets
      secretNamespace: security
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          intermediate_ca_key: '{{ .INTERMEDIATE_CA_KEY.Value }}'
          ssh_user_ca_key: '{{ .SSH_USER_CA_KEY.Value }}'
          ssh_host_ca_key: '{{ .SSH_HOST_CA_KEY.Value }}'
    - secretName: step-ca-step-certificates-ca-password
      secretNamespace: security
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          password: '{{ .CA_PASSWORD.Value }}'
    - secretName: step-ca-step-certificates-certificate-issuer-password
      secretNamespace: security
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          password: '{{ .PROVISIONER_PASSWORD.Value }}'
    - secretName: step-ca-step-certificates-ssh-user-ca-password
      secretNamespace: security
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          password: '{{ .CA_PASSWORD.Value }}'
    - secretName: step-ca-step-certificates-ssh-host-ca-password
      secretNamespace: security
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          password: '{{ .CA_PASSWORD.Value }}'
