---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-${APP}
spec:
  postgresql:
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
