---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app red-lavalink
spec:
  dependsOn:
    - name: infisical-operator
      namespace: security
  interval: 1h
  path: ./kubernetes/apps/communication/red-lavalink
  postBuild:
    substitute:
      APP: *app
      NS: &ns communication
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *ns
  wait: false
