---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      lidarr:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/lidarr
              tag: nightly-version-3.1.2.4928@sha256:034055feee43b11eb2f7a8438a9af1c99ab564dd2b43e5df2fe5b3c9b3b8b1ac
            env:
              LIDARR__APP__INSTANCENAME: Lidarr
              LIDARR__APP__THEME: dark
              LIDARR__AUTH__METHOD: External
              LIDARR__AUTH__REQUIRED: DisabledForLocalAddresses
              LIDARR__LOG__DBENABLED: "False"
              LIDARR__LOG__LEVEL: info
              LIDARR__SERVER__PORT: &port 8686
              LIDARR__UPDATE__BRANCH: develop
              LIDARR__POSTGRES__HOST: pooler-lidarr-rw
              LIDARR__POSTGRES__PORT: "5432"
              LIDARR__POSTGRES__MAINDB:
                valueFrom:
                  secretKeyRef:
                    name: &pg postgres-lidarr-app
                    key: dbname
              LIDARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *pg
                    key: password
              LIDARR__POSTGRES__USER:
                valueFrom:
                  secretKeyRef:
                    name: *pg
                    key: username
              # LinuxServer K8s compat
              PUID: "1000"
              PGID: "100"
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"
              S6_READ_ONLY_ROOT: "1"
              LSIO_READ_ONLY_FS: "1"
              LSIO_NON_ROOT_USER: "1"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: downloads
        hostnames:
          - "{{ .Release.Name }}.vzkn.eu"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: aincrad.home.vzkn.eu
        path: /mnt/cache/z_media
        globalMounts:
          - path: /data/media
            subPath: music
      soulseek:
        type: nfs
        server: aincrad.home.vzkn.eu
        path: /mnt/user/data/soulseek
        globalMounts:
          - path: /soulseek
      deemix:
        type: nfs
        server: aincrad.home.vzkn.eu
        path: /mnt/user/data/deemix
        globalMounts:
          - path: /deemix
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /config/logs
            subPath: logs
          - path: /run
            subPath: run
