---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./toolhive/ks.yaml
  - ./mcp/siderolabs-docs/ks.yaml
  - ./mcp/sentry/ks.yaml
  - ./mcp/kubernetes/ks.yaml
  - ./mcp/forgejo/ks.yaml
