---
# NOTE: Multi-source - configure Secret Import in Infisical for: /terraform/garage/buckets (BLUESKY_ACCESS_KEY_ID/SECRET)
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name bluesky-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/social/bluesky
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: social
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          COCOON_ADMIN_PASSWORD: '{{ .ADMIN_PASSWORD.Value }}'
          COCOON_SESSION_SECRET: '{{ .JWT_SECRET.Value }}'
          COCOON_S3_ACCESS_KEY: '{{ .BLUESKY_ACCESS_KEY_ID.Value }}'
          COCOON_S3_SECRET_KEY: '{{ .BLUESKY_SECRET_ACCESS_KEY.Value }}'
