---
# NOTE: Multi-source - configure Secret Imports in Infisical for: nextcloud-talk, coturn
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name nextcloud-talk-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/self-hosted/nextcloud
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: self-hosted
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          server.conf: |-
            [http]
            listen = 0.0.0.0:8080

            [app]
            debug = false

            [sessions]
            hashkey = {{ .SIGNALING_SECRET.Value | substr 0 32 }}
            blockkey = {{ .SIGNALING_SECRET.Value | substr 0 32 }}

            [clients]
            internalsecret = {{ .INTERNAL_SECRET.Value }}

            [backend]
            backends = nextcloud
            allowall = false
            timeout = 10
            connectionsperhost = 8

            [nextcloud]
            url = https://cloud.vzkn.eu
            secret = {{ .INTERNAL_SECRET.Value }}

            [nats]
            url = nats://nextcloud-talk-nats:4222

            [turn]
            apikey = {{ .TURN_SECRET.Value }}
            secret = {{ .TURN_SECRET.Value }}
            servers = turn:turn.vzkn.eu:3478?transport=udp,turn:turn.vzkn.eu:3478?transport=tcp,turns:turn.vzkn.eu:5349?transport=tcp
