---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./attic/ks.yaml
  - ./defectdojo/ks.yaml
  - ./forgejo/ks.yaml
  - ./zot/ks.yaml
