---
# NOTE: Multi-source - configure Secret Imports in Infisical for: forgejo, /terraform/garage/buckets, protonmail
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name forgejo-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/development/forgejo
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: development
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          SECRET_KEY: '{{ .SECRET_KEY.Value }}'
          # CF_TURNSTILE_SITEKEY: '{{ .CF_TURNSTILE_SITEKEY.Value }}'
          # CF_TURNSTILE_SECRET: '{{ .CF_TURNSTILE_SECRET.Value }}'
          SMTP_ADDR: '{{ .SMTP_ADDR.Value }}'
          USER: '{{ .SMTP_USER.Value }}'
          PASSWD: '{{ .SMTP_PASS.Value }}'
          MINIO_ACCESS_KEY_ID: '{{ .FORGEJO_ACCESS_KEY_ID.Value }}'
          MINIO_SECRET_ACCESS_KEY: '{{ .FORGEJO_SECRET_ACCESS_KEY.Value }}'

---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name forgejo-admin-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/development/forgejo
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: development
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          username: '{{ .ADMIN_USERNAME.Value }}'
          password: '{{ .ADMIN_PASSWORD.Value }}'

---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name forgejo-authentik-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/development/forgejo
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: development
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          key: '{{ .FORGEJO_CLIENT_ID.Value }}'
          secret: '{{ .FORGEJO_CLIENT_SECRET.Value }}'
