---
# yaml-language-server: $schema=https://schemas.vzkn.eu/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-${APP}
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: kafka-${APP}
  namespaceSelector:
    matchNames:
      - ${NS:=${APP}}
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
