---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # https://github.com/tektoncd/pipelines-as-code/releases
  # renovate: depName=tektoncd/pipelines-as-code datasource=github-releases
  - https://github.com/tektoncd/pipelines-as-code/releases/download/v0.46.0/release.k8s.yaml
patches:
  - target:
      kind: ConfigMap
      name: pipelines-as-code
      namespace: pipelines-as-code
    patch: |-
      - op: replace
        path: /data/tekton-dashboard-url
        value: https://tekton.vzkn.eu
      - op: replace
        path: /data/application-name
        value: Tekton CI
