---
# NOTE: Multi-source - configure Secret Imports in Infisical for:
# radarr, radarr-anime, sonarr, sonarr-anime
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name recyclarr-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/downloads/recyclarr
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: downloads
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          RADARR_API_KEY: '{{ .RADARR_API_KEY.Value }}'
          RADARR_ANIME_API_KEY: '{{ .RADARR_ANIME_API_KEY.Value }}'
          SONARR_API_KEY: '{{ .SONARR_API_KEY.Value }}'
          SONARR_ANIME_API_KEY: '{{ .SONARR_ANIME_API_KEY.Value }}'
    - secretName: recyclarr-config
      secretNamespace: downloads
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          recyclarr.yml: '{{ .RECYCLARR_CONFIG.Value }}'
