---
# yaml-language-server: $schema=https://schemas.vzkn.eu/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: &name letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: *name
    profile: shortlived
    solvers:
      - dns01:
          webhook:
            groupName: acme.vzkn.eu
            solverName: ovh
            config:
              endpoint: ovh-eu
              authenticationMethod: application
              applicationKeyRef:
                key: applicationKey
                name: ovh-issuer-secret
              applicationSecretRef:
                key: applicationSecret
                name: ovh-issuer-secret
              applicationConsumerKeyRef:
                key: consumerKey
                name: ovh-issuer-secret
        selector:
          dnsZones:
            - vzkn.eu
