---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name lavalink-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/communication/redbot
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: ${NS}
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          LAVALINK_SERVER_PASSWORD: '{{ .LAVALINK_SERVER_PASSWORD.Value }}'
          PLUGINS_LAVASRC_DEEZER_MASTERDECRYPTIONKEY: '{{ .DEEZER_MASTER_DECRYPTION_KEY.Value }}'
