---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
spec:
  discoveryFilters:
    - "vrozaksen/*"
  provider:
    name: forgejo
    endpoint: https://git.vzkn.eu
  image: ghcr.io/renovatebot/renovate:43.249.7@sha256:4f80d7ab8a9f7d481a0013c5ab33de52d510e4605e3e43968b234ef3f3e72ac4
  schedule: "0 * * * *"
  parallelism: 3
  secretRef: renovate-forgejo-token
  extraEnv:
    - name: LOG_LEVEL
      value: info
    - name: RENOVATE_PLATFORM_COMMIT
      value: enabled
    - name: RENOVATE_AUTODISCOVER
      value: "true"
    - name: RENOVATE_AUTODISCOVER_FILTER
      value: "vrozaksen/*"
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate Bot <renovate@vzkn.eu>"
    - name: RENOVATE_USERNAME
      value: "renovate-bot"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 2Gi
  webhook:
    enabled: true
    authentication:
      enabled: false
