---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
spec:
  discoveryFilters:
    - "vrozaksen/*"
  provider:
    name: forgejo
    endpoint: https://git.vzkn.eu
  image: ghcr.io/renovatebot/renovate:44.103.6@sha256:e3b2136d970dc422acd3f574fab5b1ef92c868fe5e89bdb7a42c0062866eb706
  schedule: "0 * * * *"
  parallelism: 3
  secretRef: renovate-forgejo-token
  extraEnv:
    - name: LOG_LEVEL
      value: info
    - name: RENOVATE_PLATFORM_COMMIT
      value: enabled
    - name: RENOVATE_AUTODISCOVER
      value: "true"
    - name: RENOVATE_AUTODISCOVER_FILTER
      value: "vrozaksen/*"
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate Bot <renovate@vzkn.eu>"
    - name: RENOVATE_USERNAME
      value: "renovate-bot"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 2Gi
  webhook:
    enabled: true
    authentication:
      enabled: false
