---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
spec:
  discoveryFilters:
    - "vrozaksen/*"
  provider:
    name: github
  image: ghcr.io/renovatebot/renovate:43.191.2@sha256:5726d7904e0e31092d75d7a535a07a615fbc3d67c8de4f76daeee21ef6e7953f
  schedule: "0 * * * *"
  parallelism: 3
  secretRef: renovate-token
  extraEnv:
    - name: LOG_LEVEL
      value: info
    - name: RENOVATE_PLATFORM_COMMIT
      value: enabled
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  webhook:
    enabled: true
    authentication:
      enabled: false
