---
# yaml-language-server: $schema=https://schemas.vzkn.eu/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stunner
spec:
  chartRef:
    kind: OCIRepository
    name: stunner
  interval: 1h
  values:
    standardCrds:
      enabled: false
    stunnerGatewayOperator:
      dataplane:
        spec:
          enableMetricsEndpoint: true
