---
# NOTE: Multi-source - configure Secret Import in Infisical for: /terraform/authentik/oidc (GOTOSOCIAL_CLIENT_ID/SECRET)
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name gotosocial-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/social/gotosocial
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: social
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          GTS_OIDC_CLIENT_ID: '{{ .GOTOSOCIAL_CLIENT_ID.Value }}'
          GTS_OIDC_CLIENT_SECRET: '{{ .GOTOSOCIAL_CLIENT_SECRET.Value }}'
