---
# NOTE: Multi-source - configure Secret Imports in Infisical for: pushover, seerr, radarr, sonarr
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name webhook-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/downloads/webhook
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: downloads
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          APPRISE_SEERR_PUSHOVER_URL: 'pover://{{ .PUSHOVER_USER_KEY.Value }}@{{ .SEERR_PUSHOVER_TOKEN.Value }}'
          APPRISE_RADARR_PUSHOVER_URL: 'pover://{{ .PUSHOVER_USER_KEY.Value }}@{{ .RADARR_PUSHOVER_TOKEN.Value }}'
          APPRISE_SONARR_PUSHOVER_URL: 'pover://{{ .PUSHOVER_USER_KEY.Value }}@{{ .SONARR_PUSHOVER_TOKEN.Value }}'
