---
# NOTE: Multi-source - configure Secret Imports in Infisical for: rxresume, rxresume-bucket, protonmail
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name rxresume-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/self-hosted/rxresume
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: self-hosted
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          AUTH_SECRET: '{{ .AUTH_SECRET.Value }}'
          SMTP_HOST: '{{ .SMTP_ADDR.Value }}'
          SMTP_PORT: "587"
          SMTP_USER: '{{ .SMTP_USER.Value }}'
          SMTP_PASS: '{{ .SMTP_PASS.Value }}'
          SMTP_FROM: 'Reactive Resume <{{ .SMTP_USER.Value }}>'
          S3_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID.Value }}'
          S3_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY.Value }}'
          FLAG_DISABLE_SIGNUPS: "false"
          FLAG_DISABLE_EMAIL_AUTH: "true"
          OAUTH_PROVIDER_NAME: "Authentik"
          OAUTH_CLIENT_ID: '{{ .RXRESUME_CLIENT_ID.Value }}'
          OAUTH_CLIENT_SECRET: '{{ .RXRESUME_CLIENT_SECRET.Value }}'
          OAUTH_DISCOVERY_URL: "https://sso.vzkn.eu/application/o/reactive-resume/.well-known/openid-configuration"
