---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name ovh-dns
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/network/ovh-dns
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: network
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          OVH_APPLICATION_KEY: "{{ .OVH_APPLICATION_KEY.Value }}"
          OVH_APPLICATION_SECRET: "{{ .OVH_APPLICATION_SECRET.Value }}"
          OVH_CONSUMER_KEY: "{{ .OVH_CONSUMER_KEY.Value }}"
