---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name deemix-vpn-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/downloads/deemix-vpn
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: downloads
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          WIREGUARD_PRIVATE_KEY: '{{ .WIREGUARD_PRIVATE_KEY.Value }}'
          WIREGUARD_ADDRESSES: '{{ .WIREGUARD_ADDRESSES.Value }}'
