---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    # CDI sets a restricted securityContext on all its pods; importer pods run
    # in the namespace of the DataVolume, not here.
    cdi.kubevirt.io: ""
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
