---
# NOTE: Multi-source - configure Secret Imports in Infisical for: sentry, /terraform/garage/buckets, protonmail, clickhouse
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name sentry-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/sentry/sentry
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: sentry
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          SENTRY_SECRET_KEY: '{{ .SECRET_KEY.Value }}'
          ADMIN_PASSWORD: '{{ .ADMIN_PASSWORD.Value }}'
          s3-access-key-id: '{{ .SENTRY_ACCESS_KEY_ID.Value }}'
          s3-secret-access-key: '{{ .SENTRY_SECRET_ACCESS_KEY.Value }}'
          mail-password: '{{ .SMTP_PASS.Value }}'
          clickhouse-password: '{{ .CLICKHOUSE_PASSWORD.Value }}'

---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name sentry-maxmind
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/sentry/sentry
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: sentry
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          MAXMIND_ACCOUNT_ID: '"{{ .MAXMIND_USER_ID.Value }}"'
          MAXMIND_LICENSE_KEY: '{{ .MAXMIND_LICENSE_KEY.Value }}'

---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name sentry-github
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/sentry/sentry
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: sentry
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          GITHUB_APP_ID: '{{ .GITHUB_APP_ID.Value }}'
          GITHUB_APP_NAME: "sentry-vzkn-eu"
          GITHUB_PRIVATE_KEY: '{{ .GITHUB_PRIVATE_KEY.Value }}'
          GITHUB_WEBHOOK_SECRET: '{{ .GITHUB_WEBHOOK_SECRET.Value }}'
          GITHUB_CLIENT_ID: '{{ .GITHUB_CLIENT_ID.Value }}'
          GITHUB_CLIENT_SECRET: '{{ .GITHUB_CLIENT_SECRET.Value }}'
