---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name volsync-maintenance-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/storage/volsync
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: storage
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          KOPIA_FS_PATH: "/repository"
          KOPIA_PASSWORD: '{{ .KOPIA_PASSWORD.Value }}'
          KOPIA_REPOSITORY: "filesystem:///repository"
