---
# yaml-language-server: $schema=https://schemas.vzkn.eu/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
spec:
  enabled: true
  trigger:
    schedule: 30 3,15 * * *
  moverVolumes:
    - mountPath: repository
      volumeSource:
        nfs:
          path: /mnt/blaze/volsync-kopia
          server: aincrad.home.vzkn.eu
  repository:
    repository: volsync-maintenance-secret
