---
# yaml-language-server: $schema=https://schemas.vzkn.eu/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: kubernetes-mcp
spec:
  image: ghcr.io/containers/kubernetes-mcp-server:v0.0.62
  transport: streamable-http
  mcpPort: 8080
  args:
    - --port=8080
    - --read-only
    - --disable-destructive
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  serviceAccount: kubernetes-mcp
