---
# NOTE: Multi-source - configure Secret Imports in Infisical for: cloudnative-pg, cnpg-bucket
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name ${APP}-cnpg-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /shared/cnpg
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: ${NS}
      secretType: Opaque
      template:
        includeAllSecrets: false
        metadata:
          labels:
            cnpg.io/reload: 'true'
        data:
          username: '{{ .POSTGRES_SUPER_USER.Value }}'
          password: '{{ .POSTGRES_SUPER_PASS.Value }}'
          AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID.Value }}'
          AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY.Value }}'
          AWS_DEFAULT_REGION: "eu-central-1"
