---
# NOTE: Multi-source - configure Secret Imports in Infisical for: lidarr, slskd
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name soularr-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/downloads/soularr
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: downloads
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          config.ini: |-
            [Lidarr]
            api_key = {{ .LIDARR_API_KEY.Value }}
            host_url = http://lidarr.downloads.svc.cluster.local:8686
            download_dir = /soulseek/complete
            disable_sync = False

            [Slskd]
            api_key = {{ .SLSKD_API_KEY.Value }}
            host_url = http://slskd:80
            url_base = /
            download_dir = /soulseek/complete
            delete_searches = False
            stalled_timeout = 3600
            remote_queue_timeout = 300

            [Release Settings]
            use_most_common_tracknum = True
            allow_multi_disc = True
            accepted_countries = Europe,Japan,Poland,United Kingdom,United States,[Worldwide],Australia,Canada
            skip_region_check = False
            accepted_formats = CD,Digital Media,Vinyl

            [Search Settings]
            search_timeout = 5000
            maximum_peer_queue = 50
            minimum_peer_upload_speed = 10000000
            minimum_filename_match_ratio = 0.7
            allowed_filetypes = flac 24/192,flac 16/44.1,flac,mp3 320,mp3
            ignored_users =
            search_for_tracks = True
            album_prepend_artist = False
            track_prepend_artist = True
            search_type = incrementing_page
            number_of_albums_to_grab = 10
            remove_wanted_on_failure = False
            title_blacklist =
            search_blacklist =
            search_source = missing
            enable_search_denylist = True
            max_search_failures = 3

            [Download Settings]
            download_filtering = True
            use_extension_whitelist = False
            extensions_whitelist = lrc,nfo,txt

            [Logging]
            ; TODO: switch to INFO once stable
            level = DEBUG
            format = [%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s
            datefmt = %Y-%m-%dT%H:%M:%S%z
