---
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name gatus-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /vps/bifrost
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: observability
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          BIFROST_HEARTBEAT_TOKEN: "{{ .BIFROST_HEARTBEAT_TOKEN.Value }}"
          VPS_IP: "{{ .VPS_IP.Value }}"
