{
 "title": "APC PDU",
 "tags": [
  "pdu",
  "power"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rPDULoadStatusLoad / 10", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Est. Power (230V)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rPDULoadStatusLoad / 10 * 230", "legendFormat": "Power" }
   ]
  },
  {
   "title": "Phase State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rPDULoadStatusLoadState", "legendFormat": "State" }
   ]
  },
  {
   "title": "Outlets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rPDUOutletStatusOutletState", "legendFormat": "{{ outlet_name }}" }
   ]
  },
  {
   "title": "Load over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "rPDULoadStatusLoad / 10", "legendFormat": "Phase load" }
   ]
  },
  {
   "title": "Outlet history",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 5 },
   "targets": [
    { "expr": "rPDUOutletStatusOutletState", "legendFormat": "{{ outlet_name }}" }
   ]
  }
 ]
}