---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./scaledobject.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
          - kustomize:
              patches:
                - target:
                    kind: ${CONTROLLER:=Deployment}
                    name: ${APP}
                  patch: |-
                    kind: ${CONTROLLER:=Deployment}
                    metadata:
                      name: ${APP}
                      labels:
                        autoscale.keda.io/nfs: "true"
                    spec:
                      template:
                        metadata:
                          labels:
                            autoscale.keda.io/nfs: "true"
