---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app redbot
spec:
  components:
    - ../../../components/kopiur
  dependsOn:
    - name: infisical-operator
      namespace: security
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/communication/redbot
  postBuild:
    substitute:
      APP: *app
      NS: &ns communication
      KOPIUR_CAPACITY: 20Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *ns
  wait: false
