---
name: auth
services:
  authentik-proxy:
    image: ghcr.io/goauthentik/proxy:2026.2.2@sha256:c5d94719cf629d1b4a06475450f71a5aacdf49f7c1003caad42da32e3aa28234
    container_name: authentik-proxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m
    env_file: /opt/pangolin/.env
    environment:
      AUTHENTIK_HOST: https://sso.vzkn.eu
      AUTHENTIK_INSECURE: "false"
    networks:
      - pangolin

networks:
  pangolin:
    external: true
