---
name: auth
services:
  authentik-proxy:
    image: ghcr.io/goauthentik/proxy:2026.2.3@sha256:e37186957e16a956e078302af73ced7045c956fcd2574107b4acdb6f929e4d36
    container_name: authentik-proxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m
    env_file: /opt/pangolin/.env
    environment:
      AUTHENTIK_HOST: https://sso.vzkn.eu
      AUTHENTIK_INSECURE: "false"
    networks:
      - pangolin

networks:
  pangolin:
    external: true
