---
# NOTE: Multi-source - configure Secret Imports in Infisical for: pushover, alertmanager
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name alertmanager-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/observability/kube-prometheus-stack
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: observability
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          ALERTMANAGER_HEARTBEAT_URL: '{{ .ALERTMANAGER_HEARTBEAT_URL.Value }}'
          ALERTMANAGER_PUSHOVER_TOKEN: '{{ .ALERTMANAGER_PUSHOVER_TOKEN.Value }}'
          PUSHOVER_USER_KEY: '{{ .PUSHOVER_USER_KEY.Value }}'
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &name vps-prometheus-secret
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/observability/kube-prometheus-stack
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: *name
      secretNamespace: observability
      secretType: Opaque
      template:
        includeAllSecrets: false
        data:
          username: '{{ .VPS_PROMETHEUS_USER.Value }}'
          password: '{{ .VPS_PROMETHEUS_PASSWORD.Value }}'
