---
# yaml-language-server: $schema=https://schemas.vzkn.eu/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: volsync
spec:
  groups:
    - name: volsync.rules
      rules:
        - alert: VolSyncComponentAbsent
          expr: |-
            absent(up{job="volsync-metrics"})
          annotations:
            summary: >-
              VolSync component has disappeared from Prometheus target discovery
          for: 5m
          labels:
            severity: critical

        - alert: VolSyncVolumeOutOfSync
          expr: |-
            volsync_volume_out_of_sync == 1
          annotations:
            summary: >-
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} volume is out of sync
          for: 5m
          labels:
            severity: critical

    - name: pvc.rules
      rules:
        - alert: PersistentVolumeClaimUnused
          expr: |-
            kube_persistentvolumeclaim_status_phase{phase="Bound", persistentvolumeclaim!~"volsync-.*-dst-dest"} == 1
            unless on (namespace, persistentvolumeclaim)
            kube_pod_spec_volumes_persistentvolumeclaims_info
          annotations:
            summary: >-
              PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is bound but not mounted by any pod
          for: 24h
          labels:
            severity: warning
