---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Terraform Diff"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changed-terraform:
    name: Changed Terraform
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-terraform.outputs.all_changed_and_modified_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Get Changed Terraform
        id: changed-terraform
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323  # v47.0.5
        with:
          files: terraform/**
          dir_names: true
          dir_names_max_depth: 2
          matrix: true

      - name: List All Changed Terraform
        run: echo ${{ steps.changed-terraform.outputs.all_changed_and_modified_files }}

  sync:
    name: Terraform Diff
    permissions:
      contents: read
      pull-requests: write
    runs-on:
      - home-ops-runner
    needs:
      - "changed-terraform"
    strategy:
      matrix:
        paths: ${{ fromJSON(needs.changed-terraform.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf  # v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Opentofu
        uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f  # v1.0.8
        env:
          RUNNER_TOOL_CACHE: /tmp/runner-tool-cache
        with:
          tofu_wrapper: false

      - name: Tofu fmt
        id: fmt
        working-directory: ${{ matrix.paths }}
        run: tofu fmt -check
        continue-on-error: true

      - name: Tofu Init
        id: init
        working-directory: ${{ matrix.paths }}
        run: |
          tofu init \
            -backend-config="access_key=${{ secrets.TERRAFORM_STATE_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.TERRAFORM_STATE_SECRET_KEY }}"

      - name: Tofu Validate
        id: validate
        working-directory: ${{ matrix.paths }}
        run: tofu validate -no-color

      - name: Tofu Plan
        working-directory: ${{ matrix.paths }}
        run: tofu plan -lock=false -var "infisical_client_id=${{ secrets.INFISICAL_CLIENT_ID }}" -var "infisical_client_secret=${{ secrets.INFISICAL_CLIENT_SECRET }}" -out .planfile | grep -v "Refreshing state...\|Reading...\|Read complete after"

      - name: Post PR comment
        continue-on-error: true
        uses: borchero/terraform-plan-comment@9c18ac901b5d2b58e9cbd9d1480af36e28ffaf88  # v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          planfile: .planfile
          terraform-cmd: tofu
          header: "📝 Terraform Plan for ${{ matrix.paths }}"
          working-directory: ${{ matrix.paths }}
