---
# Per-app databases inside the shared postgres-arr cluster.
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: bazarr
spec:
  cluster:
    name: postgres-arr
  name: bazarr
  owner: bazarr
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lidarr
spec:
  cluster:
    name: postgres-arr
  name: lidarr
  owner: lidarr
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: prowlarr
spec:
  cluster:
    name: postgres-arr
  name: prowlarr
  owner: prowlarr
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr
spec:
  cluster:
    name: postgres-arr
  name: radarr
  owner: radarr
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr
spec:
  cluster:
    name: postgres-arr
  name: sonarr
  owner: sonarr
