---
# Pull 5 passwords from Infisical and materialize as 5 K8s secrets in the
# format CNPG ManagedRole expects: `username` + `password` keys.
# yaml-language-server: $schema=https://schemas.vzkn.eu/secrets.infisical.com/infisicalsecret_v1alpha1.json
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres-arr-role-credentials
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: vzkn-eu-v2-zn
        envSlug: prod
        secretsPath: /kubernetes/downloads/postgres-arr
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: postgres-arr-bazarr-credentials
      secretNamespace: downloads
      secretType: kubernetes.io/basic-auth
      template:
        includeAllSecrets: false
        data:
          username: "bazarr"
          password: '{{ .BAZARR_PASSWORD.Value }}'
    - secretName: postgres-arr-lidarr-credentials
      secretNamespace: downloads
      secretType: kubernetes.io/basic-auth
      template:
        includeAllSecrets: false
        data:
          username: "lidarr"
          password: '{{ .LIDARR_PASSWORD.Value }}'
    - secretName: postgres-arr-prowlarr-credentials
      secretNamespace: downloads
      secretType: kubernetes.io/basic-auth
      template:
        includeAllSecrets: false
        data:
          username: "prowlarr"
          password: '{{ .PROWLARR_PASSWORD.Value }}'
    - secretName: postgres-arr-radarr-credentials
      secretNamespace: downloads
      secretType: kubernetes.io/basic-auth
      template:
        includeAllSecrets: false
        data:
          username: "radarr"
          password: '{{ .RADARR_PASSWORD.Value }}'
    - secretName: postgres-arr-sonarr-credentials
      secretNamespace: downloads
      secretType: kubernetes.io/basic-auth
      template:
        includeAllSecrets: false
        data:
          username: "sonarr"
          password: '{{ .SONARR_PASSWORD.Value }}'
