---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-${APP}
spec:
  bootstrap:
    initdb:
      database: ${APP}
      owner: ${APP}
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS unaccent;
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  postgresql:
    shared_preload_libraries:
      - vchord.so
